// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA61Hl6UyqhptJ-t2cR4WkdThh467GmU4U',
    appId: '1:392711834290:web:5a5590e9743f3351b797ab',
    messagingSenderId: '392711834290',
    projectId: 'todo-app-976f6',
    authDomain: 'todo-app-976f6.firebaseapp.com',
    storageBucket: 'todo-app-976f6.appspot.com',
    measurementId: 'G-JD8CDC9CEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN57GHCVqCZrrw_02RBBsnmSXOUoKoS-4',
    appId: '1:392711834290:android:d9639a2a64cdda0bb797ab',
    messagingSenderId: '392711834290',
    projectId: 'todo-app-976f6',
    storageBucket: 'todo-app-976f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDQINy0MPEjWa_apJevLdv5w7raV0ySI',
    appId: '1:392711834290:ios:e88c2ed47bd9aaafb797ab',
    messagingSenderId: '392711834290',
    projectId: 'todo-app-976f6',
    storageBucket: 'todo-app-976f6.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPDQINy0MPEjWa_apJevLdv5w7raV0ySI',
    appId: '1:392711834290:ios:eb7fcdb740af11adb797ab',
    messagingSenderId: '392711834290',
    projectId: 'todo-app-976f6',
    storageBucket: 'todo-app-976f6.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
